'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    
      // Add altering commands here.
      // Return a promise to correctly handle asynchronicity.

      // Example:
      return queryInterface.bulkInsert('People', [
        {
          "employeeId": 1054,
          "lastName": "Frenz",
          "firstName": "Dan",
          "department": "2001 - Fashion 220",
          "laborType": "Indirect - Org Level 5",
          "position": "SALES",
          "location": "Lena - South Tower - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2041,
          "lastName": "Stoll",
          "firstName": "Nicholas",
          "department": "2100 - Purchasing Department",
          "laborType": "Indirect - Org Level 4",
          "position": "MANAGER",
          "location": "South Chillicothe - North Tower - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2043,
          "lastName": "Provenzale",
          "firstName": "Paul",
          "department": "6100 - Manufacturing - Chemical Control",
          "laborType": "Indirect - Org Level 5",
          "position": "MANAGER",
          "location": "South Chillicothe - North Tower - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2073,
          "lastName": "Fletcher",
          "firstName": "Jeremy",
          "department": "2500 - Research & Development",
          "laborType": "Indirect - Org Level 7",
          "position": "LABORATORY",
          "location": "Lena - West Tower - Second Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2128,
          "lastName": "Horvath",
          "firstName": "Robert",
          "department": "3120 - Facilities - Maintenance",
          "laborType": "Indirect - Org Level 9",
          "position": "",
          "location": "",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2185,
          "lastName": "Spence",
          "firstName": "Teresa",
          "department": "7000 - Quality Assurance - Office",
          "laborType": "Indirect - Org Level 8",
          "position": "LEAD",
          "location": "South Chillicothe - North Tower - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2203,
          "lastName": "Holzheimer",
          "firstName": "Daniel",
          "department": "1225 - Corporate Management",
          "laborType": "Indirect - Org Level 3",
          "position": "DIRECTOR",
          "location": "South Chillicothe - North Tower - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2221,
          "lastName": "Nutter",
          "firstName": "Kimberley",
          "department": "6200 - Manufacturing - Pack Out",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Packout",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2226,
          "lastName": "Gregory III",
          "firstName": "Vesper",
          "department": "3120 - Facilities - Maintenance",
          "laborType": "Indirect - Org Level 8",
          "position": "LEAD",
          "location": "Lena - Warehouse - Work Shop",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2290,
          "lastName": "Orosz",
          "firstName": "Winona",
          "department": "6000 - Manufacturing - Private Label Production",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2291,
          "lastName": "Ridenbaugh",
          "firstName": "Clayton",
          "department": "6200 - Manufacturing - Pack Out",
          "laborType": "Indirect - Org Level 7",
          "position": "SUPERVISOR",
          "location": "Lena - Warehouse - Packout",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2300,
          "lastName": "Judson",
          "firstName": "Chuck",
          "department": "5130 - Fulfillment- Counting",
          "laborType": "Indirect - Org Level 7",
          "position": "SUPERVISOR",
          "location": "Lena - Warehouse - Counting",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2314,
          "lastName": "Putka",
          "firstName": "William",
          "department": "6110 - Manufacturing - Chemical Compounding",
          "laborType": "Indirect - Org Level 8",
          "position": "COMPOUNDING",
          "location": "1830 Miller - Warehouse - Compounding",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2316,
          "lastName": "Collins",
          "firstName": "Karen",
          "department": "5100 - Fulfillment- Fill Room",
          "laborType": "Direct - Org Level 9",
          "position": "LEAD",
          "location": "Lena - Warehouse - Fill Room",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2331,
          "lastName": "Owens",
          "firstName": "Faith",
          "department": "2201 - Bulk Apothecary - Loss Prevention",
          "laborType": "Indirect - Org Level 7",
          "position": "SUPERVISOR",
          "location": "Lena - South Tower - Second Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2340,
          "lastName": "Holcomb",
          "firstName": "Kenady",
          "department": "1100 - Accounting Department",
          "laborType": "Indirect - Org Level 9",
          "position": "ACCOUNTANT",
          "location": "South Chillicothe - North Tower - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2364,
          "lastName": "Hayes",
          "firstName": "John",
          "department": "6900 - Manufacturing - Production Planning",
          "laborType": "Indirect - Org Level 7",
          "position": "SUPERVISOR",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2369,
          "lastName": "Cutlip",
          "firstName": "Michael",
          "department": "7000 - Quality Assurance - Office",
          "laborType": "Indirect - Org Level 3",
          "position": "DIRECTOR",
          "location": "South Chillicothe - North Tower - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2370,
          "lastName": "Spence",
          "firstName": "Mary",
          "department": "7000 - Quality Assurance - Office",
          "laborType": "Indirect - Org Level 10",
          "position": "QUALITY ASSURANCE",
          "location": "South Chillicothe - North Tower - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2379,
          "lastName": "Putka",
          "firstName": "Brian",
          "department": "2300 - Sales - Private Label",
          "laborType": "Indirect - Org Level 9",
          "position": "SALES",
          "location": "South Chillicothe - North Tower - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2382,
          "lastName": "Evans",
          "firstName": "Scarlet",
          "department": "6000 - Manufacturing - Private Label Production",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2388,
          "lastName": "Sanders",
          "firstName": "Lisa",
          "department": "5100 - Fulfillment- Fill Room",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Fill Room",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2423,
          "lastName": "Proudfoot",
          "firstName": "Janet",
          "department": "7000 - Quality Assurance - Office",
          "laborType": "Indirect - Org Level 4",
          "position": "MANAGER",
          "location": "South Chillicothe - North Tower - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2424,
          "lastName": "Clapp",
          "firstName": "Betty",
          "department": "5100 - Fulfillment- Fill Room",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Fill Room",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2434,
          "lastName": "McCabe",
          "firstName": "Karen",
          "department": "6000 - Manufacturing - Private Label Production",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2445,
          "lastName": "Friedman",
          "firstName": "Ryan",
          "department": "6110 - Manufacturing - Chemical Compounding",
          "laborType": "Indirect - Org Level 10",
          "position": "COMPOUNDING",
          "location": "1830 Miller - Warehouse - Compounding",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2447,
          "lastName": "Davis",
          "firstName": "Lisa",
          "department": "5100 - Fulfillment- Fill Room",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Fill Room",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2452,
          "lastName": "Peppeard",
          "firstName": "Dawn",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Direct - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2456,
          "lastName": "Rouse",
          "firstName": "Cayce",
          "department": "1100 - Accounting Department",
          "laborType": "Indirect - Org Level 9",
          "position": "ACCOUNTANT",
          "location": "South Chillicothe - North Tower - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2461,
          "lastName": "Tylicki",
          "firstName": "Toni",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Direct - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2483,
          "lastName": "Ruediger",
          "firstName": "Mark",
          "department": "8200 - 1800 Facility - Warehouse",
          "laborType": "Indirect - Org Level 7",
          "position": "SUPERVISOR",
          "location": "1800 Miller - Warehouse - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2486,
          "lastName": "Phillips",
          "firstName": "Isaac",
          "department": "5110 - Manufacturing - Bulk Production",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2499,
          "lastName": "Ruby Jr",
          "firstName": "James",
          "department": "2300 - Sales - Private Label",
          "laborType": "Indirect - Org Level 9",
          "position": "SALES",
          "location": "South Chillicothe - North Tower - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2518,
          "lastName": "Carey",
          "firstName": "Paradise",
          "department": "6000 - Manufacturing - Private Label Production",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2519,
          "lastName": "Robinson",
          "firstName": "Radine",
          "department": "3000 - Manufacturing - Machine Setup",
          "laborType": "Indirect - Org Level 9",
          "position": "MAINTENANCE",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2522,
          "lastName": "Campbell",
          "firstName": "Elaine",
          "department": "6000 - Manufacturing - Private Label Production",
          "laborType": "Indirect - Org Level 6",
          "position": "SUPERVISOR",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2533,
          "lastName": "Triplett",
          "firstName": "Sheldon",
          "department": "2100 - Purchasing Department",
          "laborType": "Indirect - Org Level 9",
          "position": "PURCHASING",
          "location": "South Chillicothe - North Tower - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2542,
          "lastName": "Brannen",
          "firstName": "Robin",
          "department": "5190 - 1800 Facility - Dry Fill",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "1800 Miller - Warehouse - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2543,
          "lastName": "Smeznik",
          "firstName": "Barbara",
          "department": "7100 - Quality Control - Manufacturing",
          "laborType": "Indirect - Org Level 9",
          "position": "QUALITY CONTROL",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2673,
          "lastName": "Allen",
          "firstName": "Christa",
          "department": "1000 - Human Resources Department",
          "laborType": "Indirect - Org Level 8",
          "position": "H/R ADMINISTRATOR",
          "location": "Lena - South Tower - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2685,
          "lastName": "Wright",
          "firstName": "Renee",
          "department": "6900 - Manufacturing - Production Planning",
          "laborType": "Indirect - Org Level 8",
          "position": "LEAD",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2686,
          "lastName": "Holmberg",
          "firstName": "Heather",
          "department": "2110 - 1800 Facility - Purchasing & Sales",
          "laborType": "Indirect - Org Level 7",
          "position": "SUPERVISOR",
          "location": "1800 Miller - Office - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2695,
          "lastName": "Lund",
          "firstName": "Destani",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Direct - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2705,
          "lastName": "Sparks",
          "firstName": "Jacqueline",
          "department": "5190 - 1800 Facility - Dry Fill",
          "laborType": "Direct - Org Level 9",
          "position": "PRODUCTION",
          "location": "1800 Miller - Warehouse - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2707,
          "lastName": "Wilson",
          "firstName": "Jesse",
          "department": "1000 - Human Resources Department",
          "laborType": "Indirect - Org Level 4",
          "position": "MANAGER",
          "location": "Lena - South Tower - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2710,
          "lastName": "Tiggs",
          "firstName": "Percy",
          "department": "5110 - Manufacturing - Bulk Production",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2711,
          "lastName": "Sydenstricker",
          "firstName": "Brent",
          "department": "5130 - Fulfillment- Counting",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Counting",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2712,
          "lastName": "Stevenson",
          "firstName": "Demetrius",
          "department": "3110 - Manufacturing - Janitorial & Custodial",
          "laborType": "Indirect - Org Level 10",
          "position": "MAINTENANCE",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2720,
          "lastName": "Bonjack",
          "firstName": "Brian",
          "department": "3120 - Facilities - Maintenance",
          "laborType": "Indirect - Org Level 6",
          "position": "SUPERVISOR",
          "location": "Lena - Warehouse - Work Shop",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2743,
          "lastName": "Ballantyne",
          "firstName": "Seritha",
          "department": "2201 - Bulk Apothecary - Loss Prevention",
          "laborType": "Indirect - Org Level 9",
          "position": "CSR",
          "location": "Lena - South Tower - Second Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2751,
          "lastName": "Henrich",
          "firstName": "Steven",
          "department": "5130 - Fulfillment- Counting",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Counting",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2775,
          "lastName": "Henrich",
          "firstName": "Larissa",
          "department": "5130 - Fulfillment- Counting",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Counting",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2777,
          "lastName": "Leho",
          "firstName": "Ashley",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Indirect - Org Level 7",
          "position": "SUPERVISOR",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2778,
          "lastName": "Stiller",
          "firstName": "Daniel",
          "department": "5130 - Fulfillment- Counting",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Counting",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2786,
          "lastName": "Wells",
          "firstName": "Kyle",
          "department": "1200 - Information Technology Department",
          "laborType": "Indirect - Org Level 7",
          "position": "SUPERVISOR",
          "location": "South Chillicothe - North Tower - Second Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2791,
          "lastName": "Klembus",
          "firstName": "Mark",
          "department": "8100 - Manufacturing - Plant Warehouse",
          "laborType": "Indirect - Org Level 10",
          "position": "WAREHOUSE",
          "location": "1830 Miller - Warehouse - Dock",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2817,
          "lastName": "Cole",
          "firstName": "Stephanie",
          "department": "7000 - Quality Assurance - Office",
          "laborType": "Indirect - Org Level 8",
          "position": "LEAD",
          "location": "South Chillicothe - North Tower - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2819,
          "lastName": "Todd",
          "firstName": "Michelle",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Direct - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2822,
          "lastName": "Mayes",
          "firstName": "Dustin",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Indirect - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2827,
          "lastName": "Hayes",
          "firstName": "Ellie",
          "department": "2400 - Graphics - Office",
          "laborType": "Indirect - Org Level 8",
          "position": "LEAD",
          "location": "Lena - South Tower - Second Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2846,
          "lastName": "Ware",
          "firstName": "David",
          "department": "8200 - 1800 Facility - Warehouse",
          "laborType": "Indirect - Org Level 9",
          "position": "WAREHOUSE",
          "location": "1800 Miller - Warehouse - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2847,
          "lastName": "Wilder",
          "firstName": "Jerome",
          "department": "8015 - S & R - Receiving - Warehouse",
          "laborType": "Indirect - Org Level 9",
          "position": "WAREHOUSE",
          "location": "Lena - Warehouse - Dock",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2848,
          "lastName": "Ladd",
          "firstName": "Brenda",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Indirect - Org Level 9",
          "position": "LEAD",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2853,
          "lastName": "Bates",
          "firstName": "Romell",
          "department": "6000 - Manufacturing - Private Label Production",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2870,
          "lastName": "Klapp III",
          "firstName": "Burton",
          "department": "8100 - Manufacturing - Plant Warehouse",
          "laborType": "Indirect - Org Level 7",
          "position": "SUPERVISOR",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2871,
          "lastName": "Eckhoff",
          "firstName": "Sara",
          "department": "2400 - Graphics - Office",
          "laborType": "Indirect - Org Level 8",
          "position": "LEAD",
          "location": "Lena - South Tower - Second Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2877,
          "lastName": "Schiciano",
          "firstName": "Edward",
          "department": "1100 - Accounting Department",
          "laborType": "Indirect - Org Level 8",
          "position": "ACCOUNTANT",
          "location": "Lena - West Tower - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2880,
          "lastName": "Yankie",
          "firstName": "Wesley",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Direct - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2889,
          "lastName": "Hale",
          "firstName": "Colin",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Direct - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2890,
          "lastName": "Halling",
          "firstName": "John",
          "department": "8500 - Fulfillment - Inventory",
          "laborType": "Indirect - Org Level 8",
          "position": "LEAD",
          "location": "Lena - Warehouse - Inventory",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2943,
          "lastName": "Rand",
          "firstName": "Chris",
          "department": "5130 - Fulfillment- Counting",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Counting",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2946,
          "lastName": "Weber",
          "firstName": "Allison",
          "department": "5190 - 1800 Facility - Dry Fill",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "1800 Miller - Warehouse - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2949,
          "lastName": "Fuhrman",
          "firstName": "William",
          "department": "3100 - Facilities - Janitorial & Custodial",
          "laborType": "Indirect - Org Level 10",
          "position": "MAINTENANCE",
          "location": "Lena - Warehouse - Work Shop",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2955,
          "lastName": "Laurenzi",
          "firstName": "Donovan",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Direct - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2959,
          "lastName": "Baudo",
          "firstName": "Darlene",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Direct - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2960,
          "lastName": "Carr",
          "firstName": "Scott",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Direct - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2976,
          "lastName": "Wendell",
          "firstName": "Nicole",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Direct - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2978,
          "lastName": "Magyarics",
          "firstName": "Andrew",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Indirect - Org Level 9",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 2989,
          "lastName": "Shepard",
          "firstName": "Eric",
          "department": "8400 - Special Projects / Systems",
          "laborType": "Indirect - Org Level 4",
          "position": "MANAGER",
          "location": "Lena - Warehouse - Tower",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3012,
          "lastName": "Turnbull",
          "firstName": "Michael",
          "department": "6000 - Manufacturing - Private Label Production",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3036,
          "lastName": "Schickler",
          "firstName": "Matthew",
          "department": "8500 - Fulfillment - Inventory",
          "laborType": "Indirect - Org Level 9",
          "position": "INVENTORY",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3067,
          "lastName": "Harris",
          "firstName": "Arthur",
          "department": "5130 - Fulfillment- Counting",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Counting",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3068,
          "lastName": "Patterson",
          "firstName": "Christopher",
          "department": "7500 - Quality Assurance - Validations",
          "laborType": "Indirect - Org Level 4",
          "position": "MANAGER",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3073,
          "lastName": "Mullins",
          "firstName": "Bryan",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Indirect - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3074,
          "lastName": "Taylor",
          "firstName": "Twanisha",
          "department": "6000 - Manufacturing - Private Label Production",
          "laborType": "Indirect - Org Level 7",
          "position": "SUPERVISOR",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3077,
          "lastName": "O'Malley",
          "firstName": "Jennifer",
          "department": "5130 - Fulfillment- Counting",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Counting",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3104,
          "lastName": "Robbins",
          "firstName": "Brian",
          "department": "5130 - Fulfillment- Counting",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Counting",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3124,
          "lastName": "Neal",
          "firstName": "Angela",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Direct - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3129,
          "lastName": "Campbell",
          "firstName": "Jayme",
          "department": "2001 - Fashion 220",
          "laborType": "Indirect - Org Level 9",
          "position": "ADMIN ASST",
          "location": "Lena - South Tower - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3142,
          "lastName": "Jeffries",
          "firstName": "Shelly",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Direct - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3157,
          "lastName": "Phillips",
          "firstName": "Trevor",
          "department": "8100 - Manufacturing - Plant Warehouse",
          "laborType": "Indirect - Org Level 10",
          "position": "WAREHOUSE",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3159,
          "lastName": "Spencer",
          "firstName": "Jeffrey",
          "department": "3010 - Manufacturing - Plant Maintenance",
          "laborType": "Indirect - Org Level 9",
          "position": "MAINTENANCE",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3160,
          "lastName": "Reid",
          "firstName": "Katherine",
          "department": "1001 - Quality Assurance - Laboratory",
          "laborType": "Indirect - Org Level 8",
          "position": "LEAD",
          "location": "Lena - West Tower - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3174,
          "lastName": "Gerrick",
          "firstName": "Jill",
          "department": "2100 - Purchasing Department",
          "laborType": "Indirect - Org Level 9",
          "position": "PURCHASING",
          "location": "South Chillicothe - North Tower - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3177,
          "lastName": "Williams",
          "firstName": "Corey",
          "department": "6000 - Manufacturing - Private Label Production",
          "laborType": "Indirect - Org Level 8",
          "position": "LEAD",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3210,
          "lastName": "Wright",
          "firstName": "Maceo",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Direct - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3226,
          "lastName": "Barnett",
          "firstName": "Kevin",
          "department": "5100 - Fulfillment- Fill Room",
          "laborType": "Indirect - Org Level 6",
          "position": "SUPERVISOR",
          "location": "Lena - Warehouse - Fill Room",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3227,
          "lastName": "Barenwald",
          "firstName": "Jorg",
          "department": "6000 - Manufacturing - Private Label Production",
          "laborType": "Indirect - Org Level 4",
          "position": "MANAGER",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3260,
          "lastName": "Klimak Jr",
          "firstName": "Allan",
          "department": "6000 - Manufacturing - Private Label Production",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3263,
          "lastName": "Ruda",
          "firstName": "Joseph",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Indirect - Org Level 5",
          "position": "MANAGER",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3270,
          "lastName": "Karlovec",
          "firstName": "Devin",
          "department": "5110 - Manufacturing - Bulk Production",
          "laborType": "Direct - Org Level 9",
          "position": "PRODUCTION",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3271,
          "lastName": "Karlovec",
          "firstName": "Dayne",
          "department": "5100 - Fulfillment- Fill Room",
          "laborType": "Indirect - Org Level 9",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Fill Room",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3285,
          "lastName": "Sauto",
          "firstName": "Catherine",
          "department": "2400 - Graphics - Office",
          "laborType": "Indirect - Org Level 9",
          "position": "CSR",
          "location": "Lena - South Tower - Second Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3292,
          "lastName": "Smith",
          "firstName": "Dan",
          "department": "3010 - Manufacturing - Plant Maintenance",
          "laborType": "Indirect - Org Level 6",
          "position": "SUPERVISOR",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3297,
          "lastName": "Reid",
          "firstName": "Andrew",
          "department": "3000 - Manufacturing - Machine Setup",
          "laborType": "Indirect - Org Level 8",
          "position": "LEAD",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3299,
          "lastName": "Pamer",
          "firstName": "Ronald",
          "department": "3010 - Manufacturing - Plant Maintenance",
          "laborType": "Indirect - Org Level 9",
          "position": "MAINTENANCE",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3308,
          "lastName": "Robbins",
          "firstName": "Freddie",
          "department": "8025 - S & R - Shipping - Warehouse",
          "laborType": "Indirect - Org Level 10",
          "position": "WAREHOUSE",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3334,
          "lastName": "Lewis",
          "firstName": "Larry",
          "department": "5190 - 1800 Facility - Dry Fill",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "1800 Miller - Warehouse - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3340,
          "lastName": "Hicks",
          "firstName": "Doyle",
          "department": "6000 - Manufacturing - Private Label Production",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3349,
          "lastName": "Grant",
          "firstName": "Candra",
          "department": "6000 - Manufacturing - Private Label Production",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3350,
          "lastName": "Burns",
          "firstName": "James",
          "department": "6000 - Manufacturing - Private Label Production",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3362,
          "lastName": "Richmond",
          "firstName": "James",
          "department": "6000 - Manufacturing - Private Label Production",
          "laborType": "Indirect - Org Level 7",
          "position": "SUPERVISOR",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3363,
          "lastName": "Obitts",
          "firstName": "Morgan",
          "department": "2300 - Sales - Private Label",
          "laborType": "Indirect - Org Level 9",
          "position": "SALES",
          "location": "South Chillicothe - North Tower - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3365,
          "lastName": "Harr",
          "firstName": "Emma",
          "department": "5130 - Fulfillment- Counting",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Counting",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3370,
          "lastName": "Papp",
          "firstName": "Margie",
          "department": "2001 - Fashion 220",
          "laborType": "Indirect - Org Level 9",
          "position": "ADMIN ASST",
          "location": "South Chillicothe - North Tower - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3380,
          "lastName": "Winters",
          "firstName": "Lewis",
          "department": "8300 - Fulfillment - Warehouse",
          "laborType": "Indirect - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3382,
          "lastName": "Henderson",
          "firstName": "Rita",
          "department": "5100 - Fulfillment- Fill Room",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Fill Room",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3386,
          "lastName": "Neal",
          "firstName": "Tarikah",
          "department": "6200 - Manufacturing - Pack Out",
          "laborType": "Indirect - Org Level 8",
          "position": "LEAD",
          "location": "Lena - Warehouse - Packout",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3387,
          "lastName": "Bowman",
          "firstName": "Austin",
          "department": "1200 - Information Technology Department",
          "laborType": "Indirect - Org Level 9",
          "position": "IT",
          "location": "South Chillicothe - North Tower - Second Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3399,
          "lastName": "Huston",
          "firstName": "Connor",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Direct - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3400,
          "lastName": "Perruchon",
          "firstName": "Aron",
          "department": "8500 - Fulfillment - Inventory",
          "laborType": "Indirect - Org Level 5",
          "position": "MANAGER",
          "location": "Lena - Warehouse - Tower",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3402,
          "lastName": "Bussey",
          "firstName": "Tiffany",
          "department": "7300 - Quality Assurance - Receiving",
          "laborType": "Indirect - Org Level 9",
          "position": "QUALITY CONTROL",
          "location": "Lena - Warehouse - Dock",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3413,
          "lastName": "Price",
          "firstName": "Robert",
          "department": "8500 - Fulfillment - Inventory",
          "laborType": "Indirect - Org Level 10",
          "position": "INVENTORY",
          "location": "Lena - Warehouse - Inventory",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3418,
          "lastName": "Houston",
          "firstName": "Constance",
          "department": "2200 - Bulk Apothecary - Customer Service",
          "laborType": "Indirect - Org Level 10",
          "position": "CSR",
          "location": "Lena - South Tower - Second Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3422,
          "lastName": "Beale",
          "firstName": "Brandon",
          "department": "6000 - Manufacturing - Private Label Production",
          "laborType": "Direct - Org Level 9",
          "position": "PRODUCTION",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3423,
          "lastName": "Carlson",
          "firstName": "Megan",
          "department": "2200 - Bulk Apothecary - Customer Service",
          "laborType": "Indirect - Org Level 8",
          "position": "LEAD",
          "location": "Lena - South Tower - Second Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3424,
          "lastName": "Mitchell",
          "firstName": "Nathaniel",
          "department": "1125 - Graphics - Production",
          "laborType": "Indirect - Org Level 8",
          "position": "LEAD",
          "location": "Lena - South Tower - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3428,
          "lastName": "Burnham",
          "firstName": "Christopher",
          "department": "7500 - Quality Assurance - Validations",
          "laborType": "Indirect - Org Level 9",
          "position": "VALIDATIONS",
          "location": "Lena - West Tower - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3434,
          "lastName": "Solomon",
          "firstName": "Jesse",
          "department": "5110 - Manufacturing - Bulk Production",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3451,
          "lastName": "Owens",
          "firstName": "Rufus",
          "department": "5100 - Fulfillment- Fill Room",
          "laborType": "Indirect - Org Level 9",
          "position": "WAREHOUSE",
          "location": "Lena - Warehouse - Fill Room",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3452,
          "lastName": "Malone",
          "firstName": "Clayton",
          "department": "6000 - Manufacturing - Private Label Production",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3458,
          "lastName": "Bandy",
          "firstName": "Christine",
          "department": "6000 - Manufacturing - Private Label Production",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3463,
          "lastName": "Dunford",
          "firstName": "Kaley",
          "department": "7300 - Quality Assurance - Receiving",
          "laborType": "Indirect - Org Level 9",
          "position": "QUALITY CONTROL",
          "location": "Lena - West Tower - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3464,
          "lastName": "King",
          "firstName": "Catherine",
          "department": "6200 - Manufacturing - Pack Out",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Packout",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3466,
          "lastName": "McMahan",
          "firstName": "Leonard",
          "department": "6000 - Manufacturing - Private Label Production",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3468,
          "lastName": "Wallschleager",
          "firstName": "Trish",
          "department": "2200 - Bulk Apothecary - Customer Service",
          "laborType": "Indirect - Org Level 5",
          "position": "MANAGER",
          "location": "Lena - South Tower - Second Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3472,
          "lastName": "Gordon",
          "firstName": "Jacob",
          "department": "6200 - Manufacturing - Pack Out",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Packout",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3476,
          "lastName": "Dohm",
          "firstName": "Aaron",
          "department": "8300 - Fulfillment - Warehouse",
          "laborType": "Indirect - Org Level 6",
          "position": "SUPERVISOR",
          "location": "Lena - Warehouse - Tower",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3481,
          "lastName": "Lemons",
          "firstName": "Robert",
          "department": "6000 - Manufacturing - Private Label Production",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3486,
          "lastName": "Billmeier",
          "firstName": "Carley",
          "department": "7000 - Quality Assurance - Office",
          "laborType": "Indirect - Org Level 9",
          "position": "QUALITY ASSURANCE",
          "location": "South Chillicothe - North Tower - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3491,
          "lastName": "Bonart",
          "firstName": "Alex",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Direct - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3511,
          "lastName": "Smith",
          "firstName": "Domnici",
          "department": "8300 - Fulfillment - Warehouse",
          "laborType": "Indirect - Org Level 7",
          "position": "LEAD",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3512,
          "lastName": "Ksenyak",
          "firstName": "Margaret",
          "department": "6000 - Manufacturing - Private Label Production",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3513,
          "lastName": "Clayton",
          "firstName": "Trevor",
          "department": "6000 - Manufacturing - Private Label Production",
          "laborType": "Direct - Org Level 8",
          "position": "LEAD",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3536,
          "lastName": "Peck JR",
          "firstName": "Antone",
          "department": "6000 - Manufacturing - Private Label Production",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3538,
          "lastName": "McGregor",
          "firstName": "Brinda",
          "department": "6000 - Manufacturing - Private Label Production",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3544,
          "lastName": "Stingley",
          "firstName": "Kenneth",
          "department": "8300 - Fulfillment - Warehouse",
          "laborType": "Indirect - Org Level 9",
          "position": "WAREHOUSE",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3545,
          "lastName": "Lucas",
          "firstName": "Tiffany",
          "department": "6000 - Manufacturing - Private Label Production",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3547,
          "lastName": "Hawk",
          "firstName": "Richard",
          "department": "8090 - Manufacturing - Transportation",
          "laborType": "Indirect - Org Level 9",
          "position": "DRIVER",
          "location": "Lena - Warehouse - Dock",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3559,
          "lastName": "Dunham",
          "firstName": "Veronica",
          "department": "1001 - Quality Assurance - Laboratory",
          "laborType": "Indirect - Org Level 5",
          "position": "MANAGER",
          "location": "Lena - West Tower - Second Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3567,
          "lastName": "Kim",
          "firstName": "Kathryn",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Direct - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3569,
          "lastName": "Pochedly",
          "firstName": "Steve",
          "department": "2100 - Purchasing Department",
          "laborType": "Indirect - Org Level 8",
          "position": "PURCHASING",
          "location": "South Chillicothe - North Tower - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3574,
          "lastName": "Dixon",
          "firstName": "Andrew",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Direct - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3575,
          "lastName": "Vilar",
          "firstName": "Darci",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Direct - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3586,
          "lastName": "Ledinsky",
          "firstName": "Moira",
          "department": "5100 - Fulfillment- Fill Room",
          "laborType": "Indirect - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Fill Room",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3595,
          "lastName": "Byrnes",
          "firstName": "Megan",
          "department": "3100 - Facilities - Janitorial & Custodial",
          "laborType": "Indirect - Org Level 10",
          "position": "MAINTENANCE",
          "location": "Lena - Warehouse - Work Shop",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3597,
          "lastName": "Haslett",
          "firstName": "Michelle",
          "department": "2301 - Customer Service Sales - Bulk Apothecary",
          "laborType": "Indirect - Org Level 9",
          "position": "SALES",
          "location": "South Chillicothe - North Tower - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3601,
          "lastName": "Roper",
          "firstName": "Jasmine",
          "department": "5100 - Fulfillment- Fill Room",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3603,
          "lastName": "Moger",
          "firstName": "Sandra",
          "department": "3100 - Facilities - Janitorial & Custodial",
          "laborType": "Indirect - Org Level 9",
          "position": "MAINTENANCE",
          "location": "Lena - Warehouse - Work Shop",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3608,
          "lastName": "Steels",
          "firstName": "Mackenzie",
          "department": "2200 - Bulk Apothecary - Customer Service",
          "laborType": "Indirect - Org Level 9",
          "position": "CSR",
          "location": "Lena - South Tower - Second Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3611,
          "lastName": "Jones",
          "firstName": "Michael",
          "department": "6000 - Manufacturing - Private Label Production",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3613,
          "lastName": "Kavanagh",
          "firstName": "Lisa",
          "department": "5100 - Fulfillment- Fill Room",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Fill Room",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3629,
          "lastName": "Hewston",
          "firstName": "Patrick",
          "department": "2400 - Graphics - Office",
          "laborType": "Indirect - Org Level 9",
          "position": "CSR",
          "location": "South Chillicothe - North Tower - Second Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3631,
          "lastName": "Sugalski",
          "firstName": "Melanie",
          "department": "2400 - Graphics - Office",
          "laborType": "Indirect - Org Level 9",
          "position": "CSR",
          "location": "Lena - South Tower - Second Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3632,
          "lastName": "Sample",
          "firstName": "Morgan",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Direct - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3635,
          "lastName": "Ackerman",
          "firstName": "Charlene",
          "department": "1125 - Graphics - Production",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - South Tower - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3638,
          "lastName": "Homa",
          "firstName": "Nicole",
          "department": "5100 - Fulfillment- Fill Room",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Fill Room",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3644,
          "lastName": "Bores",
          "firstName": "Kristy",
          "department": "1200 - Information Technology Department",
          "laborType": "Indirect - Org Level 9",
          "position": "IT",
          "location": "South Chillicothe - North Tower - Second Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3645,
          "lastName": "Lynch",
          "firstName": "Cameron",
          "department": "1001 - Quality Assurance - Laboratory",
          "laborType": "Indirect - Org Level 9",
          "position": "LABORATORY",
          "location": "Lena - West Tower - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3646,
          "lastName": "Sample",
          "firstName": "Stephen",
          "department": "3000 - Manufacturing - Machine Setup",
          "laborType": "Indirect - Org Level 9",
          "position": "MAINTENANCE",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3648,
          "lastName": "Griffin",
          "firstName": "Kyler",
          "department": "6000 - Manufacturing - Private Label Production",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3651,
          "lastName": "Hayes",
          "firstName": "Darrell",
          "department": "8015 - S & R - Receiving - Warehouse",
          "laborType": "Indirect - Org Level 7",
          "position": "SUPERVISOR",
          "location": "Lena - Warehouse - Dock",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3654,
          "lastName": "Palmer",
          "firstName": "Laura",
          "department": "4800 - Customer Pickup - Bulk Apothecary",
          "laborType": "Indirect - Org Level 9",
          "position": "CSR",
          "location": "Lena - Warehouse - Customer Pickup",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3655,
          "lastName": "Brown",
          "firstName": "Stacy",
          "department": "2200 - Bulk Apothecary - Customer Service",
          "laborType": "Indirect - Org Level 10",
          "position": "CSR",
          "location": "Lena - South Tower - Second Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3661,
          "lastName": "Arnold",
          "firstName": "Penny",
          "department": "5100 - Fulfillment- Fill Room",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Fill Room",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3664,
          "lastName": "Rovtar",
          "firstName": "Robert",
          "department": "6110 - Manufacturing - Chemical Compounding",
          "laborType": "Indirect - Org Level 7",
          "position": "SUPERVISOR",
          "location": "1830 Miller - Warehouse - Compounding",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3665,
          "lastName": "Martoncik",
          "firstName": "Edward",
          "department": "8015 - S & R - Receiving - Warehouse",
          "laborType": "Indirect - Org Level 10",
          "position": "WAREHOUSE",
          "location": "Lena - Warehouse - Dock",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3668,
          "lastName": "Board",
          "firstName": "Wayne",
          "department": "3120 - Facilities - Maintenance",
          "laborType": "Indirect - Org Level 9",
          "position": "MAINTENANCE",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3669,
          "lastName": "Richardson",
          "firstName": "Lamount",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Direct - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3670,
          "lastName": "Yeranossian",
          "firstName": "Aram",
          "department": "5100 - Fulfillment- Fill Room",
          "laborType": "Indirect - Org Level 9",
          "position": "WAREHOUSE",
          "location": "Lena - Warehouse - Fill Room",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3673,
          "lastName": "Smith",
          "firstName": "Holly",
          "department": "2200 - Bulk Apothecary - Customer Service",
          "laborType": "Indirect - Org Level 9",
          "position": "CSR",
          "location": "Lena - South Tower - Second Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3675,
          "lastName": "Finnell",
          "firstName": "Jennifer",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Direct - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3678,
          "lastName": "Owens",
          "firstName": "Madara",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Direct - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3679,
          "lastName": "Shuman",
          "firstName": "Arland",
          "department": "3000 - Manufacturing - Machine Setup",
          "laborType": "Indirect - Org Level 9",
          "position": "MAINTENANCE",
          "location": "Lena - Warehouse - Work Shop",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3680,
          "lastName": "Barfield",
          "firstName": "Michael",
          "department": "6110 - Manufacturing - Chemical Compounding",
          "laborType": "Direct - Org Level 10",
          "position": "MAINTENANCE",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3682,
          "lastName": "Potluri",
          "firstName": "Poorna",
          "department": "8010 - S & R - Receiving - Office",
          "laborType": "Indirect - Org Level 8",
          "position": "LEAD",
          "location": "Lena - Warehouse - Dock",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3684,
          "lastName": "Holmes",
          "firstName": "Mauriel",
          "department": "5100 - Fulfillment- Fill Room",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Fill Room",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3686,
          "lastName": "Christy",
          "firstName": "Jamie",
          "department": "8015 - S & R - Receiving - Warehouse",
          "laborType": "Indirect - Org Level 10",
          "position": "WAREHOUSE",
          "location": "Lena - Warehouse - Dock",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3687,
          "lastName": "Rizzo",
          "firstName": "Lee",
          "department": "7100 - Quality Control - Manufacturing",
          "laborType": "Indirect - Org Level 9",
          "position": "QUALITY CONTROL",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3688,
          "lastName": "Allen",
          "firstName": "Gwendolyn",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Direct - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3689,
          "lastName": "Perry",
          "firstName": "Aundre",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Direct - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3690,
          "lastName": "Kuhns",
          "firstName": "Spencer",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Direct - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3692,
          "lastName": "Evans",
          "firstName": "Hailey",
          "department": "2200 - Bulk Apothecary - Customer Service",
          "laborType": "Indirect - Org Level 9",
          "position": "CSR",
          "location": "South Chillicothe - North Tower - Second Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3693,
          "lastName": "Goodnight",
          "firstName": "Ian",
          "department": "1200 - Information Technology Department",
          "laborType": "Indirect - Org Level 9",
          "position": "IT",
          "location": "South Chillicothe - North Tower - Second Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3694,
          "lastName": "Williams",
          "firstName": "Jasmine",
          "department": "4800 - Customer Pickup - Bulk Apothecary",
          "laborType": "Indirect - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Customer Pickup",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3695,
          "lastName": "McCullough",
          "firstName": "Sharae",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Direct - Org Level 9",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3696,
          "lastName": "Hetzel",
          "firstName": "Dion",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Direct - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3698,
          "lastName": "Dandridge",
          "firstName": "Aja",
          "department": "6200 - Manufacturing - Pack Out",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Packout",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3701,
          "lastName": "White",
          "firstName": "Justin",
          "department": "6200 - Manufacturing - Pack Out",
          "laborType": "Direct - Org Level 9",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Packout",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3702,
          "lastName": "Wilson",
          "firstName": "Adreana",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Direct - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3707,
          "lastName": "Peoples",
          "firstName": "Taushanae",
          "department": "6000 - Manufacturing - Private Label Production",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3712,
          "lastName": "Wilcher",
          "firstName": "Jammie",
          "department": "5100 - Fulfillment- Fill Room",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Fill Room",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3714,
          "lastName": "Paolillo",
          "firstName": "Frances",
          "department": "6000 - Manufacturing - Private Label Production",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3715,
          "lastName": "Gordos",
          "firstName": "Catherine",
          "department": "5100 - Fulfillment- Fill Room",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Fill Room",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3718,
          "lastName": "Hummell",
          "firstName": "Morgan",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Indirect - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3719,
          "lastName": "Zhao",
          "firstName": "Linda",
          "department": "5100 - Fulfillment- Fill Room",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Fill Room",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3720,
          "lastName": "Bennett",
          "firstName": "David",
          "department": "7100 - Quality Control - Manufacturing",
          "laborType": "Indirect - Org Level 7",
          "position": "SUPERVISOR",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3721,
          "lastName": "Morell",
          "firstName": "Michele",
          "department": "5100 - Fulfillment- Fill Room",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Fill Room",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3722,
          "lastName": "McDaniel",
          "firstName": "Laurie",
          "department": "5100 - Fulfillment- Fill Room",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3724,
          "lastName": "Brown",
          "firstName": "Lovisha",
          "department": "6200 - Manufacturing - Pack Out",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Packout",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3725,
          "lastName": "Patrick",
          "firstName": "Darrius",
          "department": "6000 - Manufacturing - Private Label Production",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3726,
          "lastName": "Handzo",
          "firstName": "Michele",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Direct - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3727,
          "lastName": "Fife",
          "firstName": "Andrew",
          "department": "8300 - Fulfillment - Warehouse",
          "laborType": "Indirect - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3731,
          "lastName": "Allen",
          "firstName": "Zachary",
          "department": "6000 - Manufacturing - Private Label Production",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3732,
          "lastName": "Malone",
          "firstName": "Valerie",
          "department": "5100 - Fulfillment- Fill Room",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Packout",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3733,
          "lastName": "Faust",
          "firstName": "Colson",
          "department": "8020 - S & R - Shipping - Office",
          "laborType": "Indirect - Org Level 9",
          "position": "WAREHOUSE",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3736,
          "lastName": "Brandt",
          "firstName": "Becky",
          "department": "8015 - S & R - Receiving - Warehouse",
          "laborType": "Indirect - Org Level 10",
          "position": "WAREHOUSE",
          "location": "Lena - Warehouse - Dock",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3737,
          "lastName": "Moss",
          "firstName": "Chante",
          "department": "6000 - Manufacturing - Private Label Production",
          "laborType": "Indirect - Org Level 10",
          "position": "PRODUCTION",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3738,
          "lastName": "Yoder",
          "firstName": "Sherri",
          "department": "8010 - S & R - Receiving - Office",
          "laborType": "Indirect - Org Level 10",
          "position": "RECEIVING CLERK",
          "location": "Lena - Warehouse - Dock",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3739,
          "lastName": "Basham",
          "firstName": "Shirley",
          "department": "5130 - Fulfillment- Counting",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Counting",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3740,
          "lastName": "Thompson",
          "firstName": "Jodie",
          "department": "2200 - Bulk Apothecary - Customer Service",
          "laborType": "Indirect - Org Level 10",
          "position": "CSR",
          "location": "Lena - South Tower - Second Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3742,
          "lastName": "Mansell",
          "firstName": "Nancy",
          "department": "5100 - Fulfillment- Fill Room",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Fill Room",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3745,
          "lastName": "Costa",
          "firstName": "Karen",
          "department": "6200 - Manufacturing - Pack Out",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Packout",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3746,
          "lastName": "Persino",
          "firstName": "Lisa",
          "department": "6200 - Manufacturing - Pack Out",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Packout",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3747,
          "lastName": "Dye",
          "firstName": "Denzil",
          "department": "6000 - Manufacturing - Private Label Production",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3749,
          "lastName": "Roosa",
          "firstName": "Jennifer",
          "department": "1000 - Human Resources Department",
          "laborType": "Indirect - Org Level 7",
          "position": "H/R ADMINISTRATOR",
          "location": "Lena - South Tower - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3750,
          "lastName": "Roman",
          "firstName": "Kailey",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Direct - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3752,
          "lastName": "Pelley",
          "firstName": "Bob",
          "department": "7500 - Quality Assurance - Validations",
          "laborType": "Indirect - Org Level 8",
          "position": "LEAD",
          "location": "1800 Miller - Office - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3753,
          "lastName": "Proto",
          "firstName": "Kim",
          "department": "7000 - Quality Assurance - Office",
          "laborType": "Indirect - Org Level 9",
          "position": "QUALITY ASSURANCE",
          "location": "South Chillicothe - North Tower - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3754,
          "lastName": "Zuponcic",
          "firstName": "Tiffany",
          "department": "8010 - S & R - Receiving - Office",
          "laborType": "Indirect - Org Level 10",
          "position": "SHIPPING",
          "location": "Lena - Warehouse - Dock",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3755,
          "lastName": "Pigg",
          "firstName": "Joshua",
          "department": "5100 - Fulfillment- Fill Room",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Fill Room",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3757,
          "lastName": "Palmer",
          "firstName": "Emily",
          "department": "6000 - Manufacturing - Private Label Production",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3758,
          "lastName": "Griffin",
          "firstName": "Aimee",
          "department": "5100 - Fulfillment- Fill Room",
          "laborType": "Indirect - Org Level 9",
          "position": "LEAD",
          "location": "Lena - Warehouse - Fill Room",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3761,
          "lastName": "Branham",
          "firstName": "Amanda",
          "department": "5130 - Fulfillment- Counting",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Counting",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3763,
          "lastName": "Stafford",
          "firstName": "Brandi",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Direct - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3764,
          "lastName": "Jessel",
          "firstName": "Branson",
          "department": "8300 - Fulfillment - Warehouse",
          "laborType": "Indirect - Org Level 10",
          "position": "WAREHOUSE",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3765,
          "lastName": "Colbetzor",
          "firstName": "Clarence",
          "department": "6000 - Manufacturing - Private Label Production",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "1830 Miller - Warehouse - Manufacturing",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3766,
          "lastName": "Norsen",
          "firstName": "Sheryl",
          "department": "6200 - Manufacturing - Pack Out",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Packout",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3767,
          "lastName": "Vason",
          "firstName": "Lamar",
          "department": "1125 - Graphics - Production",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - South Tower - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3769,
          "lastName": "Barnett",
          "firstName": "Jackielyn",
          "department": "5100 - Fulfillment- Fill Room",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Fill Room",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3770,
          "lastName": "Hilles",
          "firstName": "Silva",
          "department": "5100 - Fulfillment- Fill Room",
          "laborType": "Direct - Org Level 10",
          "position": "PRODUCTION",
          "location": "Lena - Warehouse - Fill Room",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3771,
          "lastName": "Wilder",
          "firstName": "Jeremy",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Direct - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3772,
          "lastName": "Spencer",
          "firstName": "Joshua",
          "department": "8500 - Fulfillment - Inventory",
          "laborType": "Indirect - Org Level 7",
          "position": "SUPERVISOR",
          "location": "Lena - Warehouse - Inventory",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3773,
          "lastName": "Whitmore",
          "firstName": "Jerrisha",
          "department": "2200 - Bulk Apothecary - Customer Service",
          "laborType": "Indirect - Org Level 7",
          "position": "SUPERVISOR",
          "location": "Lena - South Tower - Second Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3774,
          "lastName": "Brown",
          "firstName": "Andrew",
          "department": "5100 - Fulfillment- Fill Room",
          "laborType": "Indirect - Org Level 7",
          "position": "SUPERVISOR",
          "location": "Lena - Warehouse - Fill Room",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3775,
          "lastName": "Branson",
          "firstName": "Deborah",
          "department": "7500 - Quality Assurance - Validations",
          "laborType": "Indirect - Org Level 8",
          "position": "VALIDATIONS",
          "location": "1800 Miller - Office - First Floor",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3776,
          "lastName": "Lamp",
          "firstName": "Lester",
          "department": "6110 - Manufacturing - Chemical Compounding",
          "laborType": "Indirect - Org Level 10",
          "position": "COMPOUNDING",
          "location": "1830 Miller - Warehouse - Compounding",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3777,
          "lastName": "McKeown",
          "firstName": "Brandon",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Direct - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        },
        {
          "employeeId": 3778,
          "lastName": "Kuhns",
          "firstName": "Chelsea",
          "department": "4000 - Fulfillment - Pick / Pack",
          "laborType": "Direct - Org Level 10",
          "position": "FULFILLMENT",
          "location": "Lena - Warehouse - Fulfillment",
          "createdAt": "2019-04-05",
          "updatedAt": "2019-04-05"
        }
      ], {}
    );
  },

  down: (queryInterface, Sequelize) => {
    
      // Add reverting commands here.
      // Return a promise to correctly handle asynchronicity.

      // Example:
      return queryInterface.bulkDelete('People', null, {});
    
  }
};